### ISSUE TITLE
TODO: Design pcb 

### ISSUE THREAD

**Issue by FSund** [FSund/pteron-keyboard#4]
This is a long-term goal, which includes me first learning how to design pcb's, so it will probably never happen 😅

**Comment by Kraken-Jokes** [comment]
I can take a crack at it. I'm in the same boat of needing to learn first but a PCB for this thing would really make the Pteron take off 😆

**Comment by FSund** [comment]
That would be really cool. Let me know how it goes!

**Comment by Kraken-Jokes** [comment]
Alright it's been a long, arduous path full of pulling out my hair and cursing at how things don't work how I assume they should, but I've got it. True to the Pteron project, the first prototype is getting made for a pro micro with only diodes, and switches needed. Basic, but (assuming again) very functional. Here's a render of how it turned out.
![Pteron56v0 1-1](https://user-images.githubusercontent.com/67011325/111894250-e305ab80-89ce-11eb-8ce0-14b0652bf0d3.png)
I was planning to wait on the pull request until I could verify the viability of the design, but if you want to check it out before then (also an embedded 32u4/ USB-C board with THT LEDs in progress) you can look at my fork of pteron-keyboard.
The embedded version is the Pteron56v0, the pro micro drop in version is Pteron56v0-PRO MICRO

**Comment by FSund** [comment]
Thanks a lot for all your hard work, that looks really cool!

Let me know how the prototype works out. I'll definitely have to get a couple of these!

**Comment by FSund** [comment]
Work on the PCB version continues here: https://github.com/kraken-jokes/pteron-pcb

Thanks @Kraken-Jokes !
